# Generated by Django 5.2 on 2025-05-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleLemonAPI', '0006_remove_orderitem_unit_price_alter_cart_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
